### ISSUE TITLE
Reject unauthorized users from login

### ISSUE THREAD

**Issue by albertusdev** [metricsui/cloud_functions#4]
For our Batch 1 application, we should exclusively open the registration only to current active Fasilkom UI's student.

We should do this on the server-side and return a boolean flag alongside the token through the Auth function so that the client can prevent the user from our web's Dashboard.

**Comment by albertusdev** [comment]
## Actionables:
- Prevent creating user to db
- Reject 401

**Comment by rumanta** [comment]
validate
- is mahasiswa fasilkom
- npm is not null
- orgCode is not null
